name: Particle Firmware Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Particle CLI
      run: npm install -g particle-cli

    - name: Login to Particle Cloud
      env:
        PARTICLE_TOKEN: ${{ secrets.PARTICLE_TOKEN }}
      run: particle login --token $PARTICLE_TOKEN

    - name: Compile firmware
      env:
        PARTICLE_TOKEN: ${{ secrets.PARTICLE_TOKEN }}
      run: particle compile photon . --saveTo firmware.bin

    - name: Upload compiled firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware.bin
